name: mela_messenger
description: mela messenger frontend
version: 1.0.0+1

environment:
    sdk: ">=2.7.0 <3.0.0"

dependencies:
    flutter:
        sdk: flutter

    firebase_auth:
    google_sign_in:
    cupertino_icons: ^0.1.2
    flutter_webrtc: ^0.3.2
    shared_preferences:
    shared_preferences_macos:
    shared_preferences_web:
    http: ^0.12.0+4
    fluttertoast:

dev_dependencies:
    flutter_test:
        sdk: flutter

flutter:
    uses-material-design: true
